Login
rov9/ecom-xpress pull request #3
Opened 2022-02-19 08:25 UTC by rov9

Please review.Live url:https://cocky-pare-3dfb7c.netlify.app/

2022-02-19 17:21 UTC, ravikumar0403 requested changes

2022-02-19 17:21 UTC, ravikumar0403 commented on index.html
> +    <title>Document</title>
Change the title to be relevant with your page

2022-02-19 17:21 UTC, ravikumar0403 commented on style.css
> +#name,#email,#password,#mob-no{
Not mandatory but it's better to avoid id for styling and use class

2022-02-19 17:21 UTC, ravikumar0403 commented on style.css
> +    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.01);
Use variables for color

2022-02-20 09:43 UTC, rov9 commented
Authorization Page-Login

2022-02-22 05:12 UTC, merged